profile: null
region: ap-northeast-1
versioning: false
default_alias: master
configuration:
  name: kipi-mabi-crawler
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: crawler.lambda_handler
  description: Kipi Mabinogi Crawler
  timeout: 180
  memory_size: 128
