profile: null
region: ap-northeast-1
versioning: false
default_alias: master
configuration:
  name: kipi-mabi-moonya
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: moonya.lambda_handler
  description: Kipi Mabinogi Moonya Bot
  timeout: 60
  memory_size: 128
